### ISSUE TITLE
crawler for google scholar

### ISSUE THREAD

**Issue by alanzchen** [conferency/find-my-reviewers#9]
we need to create a crawler to get all information if a user provides his/her google scholar.

I think for this type of crawling (a few pages only) - beautiful soup might be better than scrapy

check the following sample pages on what information could be there and should be collected:

https://scholar.google.com/citations?user=onKvwjAAAAAJ&hl=en&oi=ao
https://scholar.google.com/citations?user=6x282B8AAAAJ&hl=en

**Comment by harrywang** [comment]
yes, bs is better - you can ask Floyd to do this - he wrote on before.
